import "./globals.css";
import type { Metadata } from "next";
import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'


export const metadata: Metadata = {
  title: "CERP Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="ar" dir="rtl">
      <head>
        <link rel="icon" href="/header/cerp.svg" />
      </head>
      <body style={{ fontFamily: 'CustomFontName, sans-serif' }}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
