import "./globals.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import Link from "next/link";
import Image from "next/image";
import Header from '../../components/header/Header'
import Footer from '../../components/footer/Footer'
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const metadata: Metadata = {
  title: "CERP Website",
  description: "Generated by create next app",
};
type Locale = 'en' | 'ar';

export default async function RootLayout({ children, params }: { children: React.ReactNode; params: Promise<{ locale: string }>; }) {
  const { locale } = await params;
  const messages = await getMessages();
  if (!routing.locales.includes(locale as Locale) || !messages) {
    notFound();
  }
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <head>
        <link rel="icon" href="/header/CERP.svg" />
      </head>
      <body className="font-tajawalregular font-bold">
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main>
            {children}
            <ToastContainer />
          </main>
          <Footer />
          <div style={{
            position: "fixed",
            left: "2rem",
            bottom: "5rem",
            zIndex: 1000,
          }}>
            <Link href="https://wa.me/+9660537802802" target="_blank" className="block lg:hidden">
              <Image src="/footer/whatsapp.png" alt="..." width={60} height={20} />
            </Link>
            <Link href="https://web.whatsapp.com/send?phone=+9660537802802" target="_blank" className="hidden lg:block">
              <Image src="/footer/whatsapp.png" alt="..." width={60} height={20} />
            </Link>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
